#!/bin/bash

rsync -av \
  ./paper.css \
  ./paper.js \
  ./fonts \
  www.xaipete.gr:/var/www/html/

ssh www.xaipete.gr mkdir -p /var/www/html/paper
rsync -av \
  example/ \
  www.xaipete.gr:/var/www/html/paper/
